[build]
  functions = "netlify/functions"
  command = "npm run build"

[dev]
  framework = "create-react-app"
  command = "npm run dev"
  targetPort = 3000
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200