[build]
  command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/products"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  included_files = ["netlify/functions/db.json"]
